 

 
export const GET_BRANDS_BYID_REQUEST = "GET_BRANDS_BYID_REQUEST";
export const GET_BRANDS_BYID_SUCCESS = "GET_BRANDS_BYID_SUCCESS";
export const GET_BRANDS_BYID_FAILURE = "GET_BRANDS_BYID_FAILURE";

 