 
export const GET_INFLUENCERS_REQUEST = "GET_INFLUENCERS_REQUEST";
export const GET_INFLUENCERS_SUCCESS = "GET_INFLUENCERS_SUCCESS";
export const GET_INFLUENCERS_FAILURE = "GET_INFLUENCERS_FAILURE";

 